export const HEADER_TITLE_DEFAULT = "EazeAccounts";
export const DTPAGE_SIZE = [10, 50, 100, 200, 500, 1000];
export const CONSTANTS = {
  moduleFontSize: "14px",
  fontSize: "13px",
  iconSize: "24px",
  fontSizeReg: "18px",
  fontSizeMid: "24px",
  fontSizeLarge: "32px",
  fontSizeExLarge: "42px",
  fontSizeCompany: "16px",
  companyNameLocalStorage: "ul-current-company",
  tokenLocalStorage: "ultra-token",
  localStorageTheme: "ultra_default_theme_color",
};

export const MENU_LIST = [
  {
    id: 1,
    title: "Dashboard",
    link: "/dashboard",
    addInPlan: true,
    module_included: true,
    permissions: { create: true, delete: true, edit: true, view: true },
    // icon: <SpeedRoundedIcon />,
    image: "sidebar/dashboard.png",
  },
  {
    id: 2,
    title: "Banking",
    link: "/banking",
    addInPlan: false,
    module_included: true,
    permissions: { create: true, delete: true, edit: true, view: true },
    // icon: <SpeedRoundedIcon />,
    image: "sidebar/banking.png",
    submenu: [
      {
        id: 3,
        title: "Banking Dashboard",
        link: "/banking/dashboard",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      // {
      //   id: 3,
      //   title: "Bank Account Setup",
      //   // link: "/banking?tab=bank-account-setup",
      //   link: "/banking/bank-account-setup",
      //   addInPlan: false,
      //   module_included: true,
      //   permissions: { create: true, delete: true, edit: true, view: true },
      // },
      // {
      //   id: 4,
      //   title: "Banking Overview",
      //   link: "/banking/overview",
      //   addInPlan: false,
      //   module_included: true,
      //   permissions: { create: true, delete: true, edit: true, view: true },
      // },
      // {
      //   id: 5,
      //   title: "All Transactions",
      //   link: "/banking/all-transactions",
      //   addInPlan: false,
      //   module_included: true,
      //   permissions: { create: true, delete: true, edit: true, view: true },
      // },
      {
        id: 6,
        title: "Bank Reconciliation",
        link: "/banking/bank-reconciliation",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 7,
        title: "Bank Rules & Automation",
        link: "/banking/bank-rules-automation",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
    ],
  },
  {
    id: 8,
    title: "Sales",
    link: "/sales",
    addInPlan: false,
    module_included: true,
    permissions: { create: true, delete: true, edit: true, view: true },
    // icon: <SpeedRoundedIcon />,
    image: "sidebar/sales.png",
    submenu: [
      {
        id: 9,
        title: "360 View",
        link: "/sales/360-view",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 10,
        title: "All Sales",
        link: "/sales/all-sales",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 11,
        title: "Customers",
        link: "/sales/customers",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 12,
        title: "Invoice",
        link: "/sales/invoice",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 13,
        title: "Product & Services",
        link: "/sales/product-services",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 14,
        title: "Payment Received",
        link: "/sales/payment-received",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 15,
        title: "Credit Note",
        link: "/sales/credit-note",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
    ],
  },
  {
    id: 16,
    title: "Expense",
    link: "/expense",
    addInPlan: false,
    module_included: true,
    permissions: { create: true, delete: true, edit: true, view: true },
    // icon: <SpeedRoundedIcon />,
    image: "sidebar/expense.png",
    submenu: [
      {
        id: 17,
        title: "Expense Transactions",
        link: "/expense/expense-transactions",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 18,
        title: "Bills",
        link: "/expense/bills",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 19,
        title: "Vendor Management",
        link: "/expense/vendor-management",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 20,
        title: "Contractors",
        link: "/expense/contractors",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 21,
        title: "Bill Payments",
        link: "/expense/bill-payments",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 22,
        title: "Debit Note",
        link: "/expense/debit-note",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
    ],
  },
  {
    id: 23,
    title: "Accounting",
    link: "/accounting",
    addInPlan: false,
    module_included: true,
    permissions: { create: true, delete: true, edit: true, view: true },
    // icon: <SpeedRoundedIcon />,
    image: "sidebar/accounting.png",
    submenu: [
      {
        id: 24,
        title: "Charts of Accounts",
        link: "/accounting/charts-of-accounts",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 25,
        title: "Account Type",
        link: "/accounting/account-type",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 26,
        title: "Sub Account Type",
        link: "/accounting/sub-account-type",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 27,
        title: "Detail Type",
        link: "/accounting/detail-type",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 28,
        title: "Sub Detail Type",
        link: "/accounting/sub-detail-type",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 29,
        title: "General Entries",
        link: "/accounting/general-entries",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
    ],
  },
  {
    id: 35,
    title: "Fixed Assets",
    link: "/fixed-assets",
    addInPlan: false,
    module_included: true,
    permissions: { create: true, delete: true, edit: true, view: true },
    // icon: <SpeedRoundedIcon />,
    image: "sidebar/roles.png",
    submenu: [
      {
        id: 36,
        title: "All Fixed Assets",
        link: "/fixed-assets/all-fixed-assets",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 37,
        title: "Run Depreciation",
        link: "/fixed-assets/run-depreciation",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
    ],
  },
  {
    id: 30,
    title: "Roles & Permission",
    link: "/roles-permission",
    addInPlan: false,
    module_included: true,
    permissions: { create: true, delete: true, edit: true, view: true },
    // icon: <SpeedRoundedIcon />,
    image: "sidebar/roles.png",
  },
  {
    id: 38,
    title: "Reports",
    link: "/reports",
    addInPlan: false,
    module_included: true,
    permissions: { create: true, delete: true, edit: true, view: true },
    // icon: <SpeedRoundedIcon />,
    image: "sidebar/reports.png",
  },
  {
    id: 31,
    title: "My Company",
    link: "/my-company",
    addInPlan: false,
    module_included: true,
    permissions: { create: true, delete: true, edit: true, view: true },
    // icon: <SpeedRoundedIcon />,
    image: "sidebar/accounting.png",
    submenu: [
      {
        id: 32,
        title: "All Companies",
        link: "/my-company/all-companies",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 33,
        title: "My Profile",
        link: "/profile",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
      {
        id: 34,
        title: "Employees",
        link: "/my-company/employees",
        addInPlan: false,
        module_included: true,
        permissions: { create: true, delete: true, edit: true, view: true },
      },
    ],
  },
];

export const ALL_BANKS = [
  {
    id: 113,
    bank_name: "Citibank Credit Card",
    logo: "assets/banks/citi.png",
    color: "#014879",
    deleted: 0,
  },
  {
    id: 114,
    bank_name: "Chase Bank",
    logo: "assets/banks/chase-bank.png",
    color: "#0E68AC",
    deleted: 0,
  },
  {
    id: 115,
    bank_name: "Bank of America",
    logo: "assets/banks/bank_america.png",
    color: "#012169",
  },
  {
    id: 116,
    bank_name: "Wells Fargo",
    logo: "assets/banks/fargo.png",
    color: "#A91C15",
    deleted: 0,
  },
  {
    id: 117,
    bank_name: "Capital One",
    logo: "assets/banks/capital-one.png",
    color: "#014879",
    deleted: 0,
  },
  {
    id: 118,
    bank_name: "U.S. Bank",
    logo: "assets/banks/us-bank.png",
    color: "#0C2174",
    deleted: 0,
  },
  {
    id: 119,
    bank_name: "Paypal",
    logo: "assets/banks/paypal.png",
    color: "#0097E6",
    deleted: 0,
  },
  {
    id: 120,
    bank_name: "Regions Bank",
    logo: "assets/banks/regions-bank.png",
    color: "#88bd40",
    deleted: 0,
  },
  {
    id: 121,
    bank_name: "Discover Credit Card",
    logo: "assets/banks/discover.png",
    color: "#F48E20",
  },
  {
    id: 122,
    bank_name: "Other Bank",
    logo: "assets/banks/plaid_icon.png",
    color: "#F48E20",
    deleted: 0,
  },
  {
    id: 173,
    bank_name: "Plaid Checking",
    logo: "assets/banks/plaid_icon.png",
    color: "#A91C15",
    deleted: 0,
  },
  {
    id: 174,
    bank_name: "Plaid Saving",
    logo: "assets/banks/plaid_icon.png",
    color: "#A91C15",
    deleted: 0,
  },
];

export const BANK_ACCOUNT_TYPE = [
  {
    value: "Checking",
    title: "Checking",
  },
  {
    value: "Saving",
    title: "Saving",
  },
  {
    value: "Certificate of Deposit",
    title: "Certificate of Deposit",
  },
  {
    value: "Merchant Account",
    title: "Merchant Account",
  },
];
export const CURRENCIES = [
  {
    value: "840",
    title: "USD",
  },
  {
    value: "INR",
    title: "INR",
  },
];
export const TRANSACTION_TYPE = [
  {
    value: "Income-Expnse",
    title: "Income / Expnse",
    for: ["money_in", "money_out"],
  },
  { value: "Deposit", title: "Deposit", for: ["money_out"] },
  { value: "Transfer", title: "Transfer", for: ["money_in", "money_out"] },
  { value: "Cheque", title: "Check", for: ["money_in"] },
  {
    value: "Credit Card Payment",
    title: "Credit Card Payment",
    for: ["money_in", "money_out"],
  },
];

export const MODAL_FORM = {
  AddAccountType: "Add Account Type",
  AddSubAccountType: "Add Sub Account Type",
  AddBank: "Add Bank",
  AddMyBankAccount: "Add Bank Account",
  AddCOA: "Add Chart of Account",
  AddProducts: "Add Product/Service",
  AddProductCategory: "Add Product Category",
  AddCustomer: "Add Customer",
  AddVendor: "Add Vendor",
  AddContractor: "Add Contractor",
  AddPayee: "Add Payee",
  ProductCategoryDetail: "Products",
  ViewInvoiceDetails: "View Invoice Details",
  AddRole: "Add Role",
  InvoiceEmailPreview: "View Invoice Email Preview",
  PricingPlan: "View Plan & Pricing",
};

export const DATE_FORMATS = [
  "DD-MM-YYYY",
  "DD-MM-YY",
  "YYYY-MM-DD",
  "YY-MM-DD",
  "MM-DD-YY",
  "MM-DD-YYYY",
  "DD/MM/YY",
  "DD/MM/YYYY",
  "MM/DD/YY",
  "MM/DD/YYYY",
  "YYYY/MM/DD",
  "YYMMDD",
  "YYYYMMDD",
  "MM.DD.YYYY",
  "MM.DD.YY",
  "DD.MM.YYYY",
  "DD.MM.YY",
  "YYYY.MM.DD",
  "DDMMYYYY",
  "MMDDYYYY",
  "YYYYMMDD",
  "MM.DD.YY",
  "DD.MM.YY",
  "YY.MM.DD",
  "DDMMYY",
  "MMDDYY",
  "MM/DDD/YYYY",
  "MM-DDD-YYYY",
  "DD-MMM-YYYY",
  "DD-MMM-YY",
  "MMM-DD-YYYY",
  "MMM-DD-YY",
  "YYYY-MMM-DD",
  "YY-MMM-DD",
  "DDMMMYYYY",
  "MMMDDYYYY",
  "YYYYMMMDD",
];

export const PAYMENT_METHOD = [
  {
    value: "Cash",
    title: "Cash",
  },
  { value: "Cheque", title: "Check" },
  { value: "Credit Card", title: "Credit Card" },
];
export const VENDOR_PAYMENT_METHOD = [
  {
    value: "ACH/Wire",
    title: "ACH/Wire",
  },
  {
    value: "Cash",
    title: "Cash",
  },
  { value: "Cheque", title: "Check" },
  { value: "Credit Card", title: "Credit Card" },
  { value: "Others", title: "Others" },
];

export const PAYMENT_TERMS = [
  {
    value: "Due on receipt",
    title: "Due on receipt",
  },
  { value: "Net 15", title: "Net 15" },
  { value: "Net 30", title: "Net 30" },
  { value: "Net 60", title: "Net 60" },
];

export const CUSTOMER_FORM_INPUTS = (close, data = null) => {
  return {
    NameContactInputs: [
      // {
      // 	id: 1,
      // 	name: "title",
      // 	label: "Title",
      // 	type: "select",
      // 	menu: "type",
      // 	size: 3,
      // 	options: data?.title || [],
      // },
      {
        id: 2,
        name: "first_name",
        label: "First Name",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 3,
        name: "middle_name",
        label: "Middle Name",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 4,
        name: "last_name",
        label: "Last Name",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 5,
        name: "company_name",
        label: "Company Name",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 6,
        name: "display_name",
        label: "Display Name",
        required: true,
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 7,
        name: "email",
        label: "Email",
        type: "email",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 8,
        name: "phone_no",
        label: "Phone Number",
        type: "phone",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 9,
        name: "mobile_no",
        label: "Mobile Number",
        type: "phone",
        size: { xs: 6, md: 3, sm: 4 },
      },
      { id: 10, name: "fax", label: "Fax", size: { xs: 6, md: 3, sm: 4 } },
      {
        id: 11,
        name: "website",
        label: "Website",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 12,
        name: "balance_sheet_account",
        label: "Balance Sheet Account",
        type: "select",
        menu: "balanceSheetAccounts",
        size: { xs: 6, md: 3, sm: 4 },
        options: data?.balance_sheet_account || [],
      },
    ],
    AddressInputs: [
      {
        billingAaddress: [
          {
            id: 1,
            name: "billing_address_1",
            label: "Street Address 1",
            size: { xs: 6, md: 3, sm: 4 },
          },
          {
            id: 2,
            name: "billing_address_2",
            label: "Street Address 2",
            size: { xs: 6, md: 3, sm: 4 },
          },
          {
            id: 3,
            name: "billing_city",
            label: "City",
            size: { xs: 6, md: 3, sm: 4 },
          },
          {
            id: 4,
            name: "billing_state",
            label: "State",
            size: { xs: 6, md: 3, sm: 4 },
          },
          {
            id: 5,
            name: "billing_zip_code",
            label: "Zip Code",
            type: "number",
            size: { xs: 6, md: 3, sm: 4 },
          },
          {
            id: 6,
            name: "billing_country",
            label: "Country",
            size: { xs: 6, md: 3, sm: 4 },
          },
        ],
      },
      {
        shippingAaddress: [
          {
            id: 1,
            name: "shipping_address_1",
            label: "Street Address 1",
            size: { xs: 6, md: 3, sm: 4 },
          },
          {
            id: 2,
            name: "shipping_address_2",
            label: "Street Address 2",
            size: { xs: 6, md: 3, sm: 4 },
          },
          {
            id: 3,
            name: "shipping_city",
            label: "City",
            size: { xs: 6, md: 3, sm: 4 },
          },
          {
            id: 4,
            name: "shipping_state",
            label: "State",
            size: { xs: 6, md: 3, sm: 4 },
          },
          {
            id: 5,
            name: "shipping_zip_code",
            label: "Zip Code",
            type: "number",
            size: { xs: 6, md: 3, sm: 4 },
          },
          {
            id: 6,
            name: "shipping_country",
            label: "Country",
            size: { xs: 6, md: 3, sm: 4 },
          },
        ],
      },
    ],
    NotesattachmentInputs: [
      { id: 1, name: "notes", label: "Notes", size: close ? 12 : 6 },
      {
        id: 2,
        name: "attachment",
        label: "Attachment",
        type: "fileUpload",
        size: close ? 12 : 6,
      },
    ],
    AchPaymentsInputs: [
      {
        id: 1,
        name: "payment_method",
        label: "Primary Payment Method",
        type: "select",
        menu: "paymentmethod",
        size: { xs: 6, md: 3, sm: 4 },
        options: data?.payment_method || [],
      },
      {
        id: 2,
        name: "payment_terms",
        label: "Terms",
        type: "select",
        menu: "paymentterms",
        size: { xs: 6, md: 3, sm: 4 },
        options: data?.payment_terms || [],
      },
    ],
    AdditionalInfoInputs: [
      {
        id: 1,
        name: "tax_rate",
        label: "Tax Rate",
        type: "number",
        size: { xs: 6, md: 3, sm: 4 },
      },
      // {
      // 	id: 2,
      // 	name: "opening_balance",
      // 	label: "Opening Balance",
      // 	type: "number",
      // 	size:3
      // },
      // {
      // 	id: 3,
      // 	name: "opening_balance_date",
      // 	label: "As Of",
      // 	type: "date",
      // 	size:3
      // },
      {
        id: 4,
        name: "income_sheet_account",
        label: "Income Account",
        type: "select",
        menu: "incomesheetaccount",
        size: { xs: 6, md: 3, sm: 4 },
        options: data?.income_sheet_account || [],
      },
    ],
  };
};
export const VENDOR_OR_CONTRACTOR_FORM_INPUTS = (close, data = null) => {
  return {
    NameContactInputs: [
      // {
      // 	id: 1,
      // 	name: "title",
      // 	label: "Title",
      // 	type: "select",
      // 	menu: "type",
      // 	size: 3,
      // },
      {
        id: 2,
        name: "first_name",
        label: "First Name",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 3,
        name: "middle_name",
        label: "Middle Name",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 4,
        name: "last_name",
        label: "Last Name",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 5,
        name: "company_name",
        label: "Company Name",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 6,
        name: "display_name",
        label: "Display Name",
        required: true,
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 7,
        name: "email",
        label: "Email",
        type: "email",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 8,
        name: "phone_no",
        label: "Phone Number",
        type: "phone",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 9,
        name: "mobile_no",
        label: "Mobile Number",
        type: "phone",
        size: { xs: 6, md: 3, sm: 4 },
      },
      { id: 10, name: "fax", label: "Fax", size: { xs: 6, md: 3, sm: 4 } },
      {
        id: 11,
        name: "website",
        label: "Website",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 12,
        name: "balance_sheet_account",
        label: "Balance Sheet Account",
        type: "select",
        menu: "balanceSheetAccounts",
        size: { xs: 6, md: 3, sm: 4 },
        options: data?.balance_sheet_account || [],
      },
      {
        id: 13,
        name: "name_to_print_on_checks",
        label: "Name To Print On Checks",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 14,
        name: "other",
        label: "Other",
        size: { xs: 6, md: 3, sm: 4 },
      },
    ],
    AddressInputs: [
      {
        id: 1,
        name: "billing_address_1",
        label: "Street Address 1",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 2,
        name: "billing_address_2",
        label: "Street Address 2",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 3,
        name: "billing_city",
        label: "City",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 4,
        name: "billing_state",
        label: "State",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 5,
        name: "billing_zip_code",
        label: "Zip Code",
        type: "number",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 6,
        name: "billing_country",
        label: "Country",
        size: { xs: 6, md: 3, sm: 4 },
      },
    ],
    NotesattachmentInputs: [
      { id: 1, name: "notes", label: "Notes", size: close ? 12 : 6 },
      {
        id: 2,
        name: "attachment",
        label: "Attachment",
        type: "fileUpload",
        size: close ? 12 : 6,
      },
    ],
    AchPaymentsInputs: [
      {
        id: 1,
        name: "ach_account_number",
        label: "ACH Account No.",
        helperText: "Account no. is usually 5-17 digits",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 2,
        name: "ach_routing_number",
        label: "Routing No",
        helperText: "Routing no. is 9 digits",
        size: { xs: 6, md: 3, sm: 4 },
      },
    ],
    AdditionalInfoInputs: [
      {
        id: 1,
        name: "tax_rate",
        label: "Taxes",
        type: "number",
        helperText: "Business ID No. / Social Security No.",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 2,
        name: "expense_rate",
        label: "Expense Rate",
        helperText: "Billing rate (/Hr)",
        type: "number",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 3,
        name: "payment_terms",
        label: "Terms",
        type: "select",
        menu: "paymentterms",
        size: { xs: 6, md: 3, sm: 4 },
        options: data?.payment_terms || [],
      },
      {
        id: 4,
        name: "expense_category",
        label: "Account No.",
        type: "number",
        size: { xs: 6, md: 3, sm: 4 },
      },
      {
        id: 5,
        name: "expense_category_id",
        label: "Default Expense Category",
        type: "select",
        menu: "balanceSheetAccounts",
        size: { xs: 6, md: 3, sm: 4 },
        options: data?.balance_sheet_account || [],
      },
      // {
      // 	id: 6,
      // 	name: "opening_balance",
      // 	label: "Opening Balance",
      // 	type: "number",
      // 	size:3
      // },
      // {
      // 	id: 7,
      // 	name: "opening_balance_date",
      // 	label: "As Of",
      // 	type: "date",
      // 	size:3
      // },
    ],
  };
};

export const REPORT_MENUS = [
  {
    title: "Business Overview",
    key: "business_overview",
    reports: [
      {
        title: "Audit Log",
        key: "audit_log",
        path: "/reports?type=audit-log",
      },
      {
        title: "Balance Sheet",
        key: "balance_sheet",
        path: "/reports?type=balance-sheet",
      },
      {
        title: "Balance Sheet Comparison",
        key: "balance_sheet_comparison",
        path: "/reports?type=balance-sheet-comparison",
      },
      {
        title: "Profit & Loss",
        key: "profit_and_loss",
        path: "/reports?type=profit-and-loss",
      },
      // {
      //   title: "Profit & Loss by Month",
      //   key: "profit_and_loss_by_month",
      //   path: "/reports?type=profit-and-loss-by-month",
      // },
      {
        title: "Profit & Loss Comparison",
        key: "profit_and_loss_comparison",
        path: "/reports?type=profit-and-loss-comparison",
      },
      // {
      //   title: "Quarterly Profit & Loss Summary",
      //   key: "quarterly_profit_and_loss_summary",
      //   path: "/reports?type=quarterly-profit-and-loss-summary",
      // },
      ,
      {
        title: "Transaction by Date",
        key: "transaction_by_date",
        path: "/reports?type=transaction-by-date",
      },
      ,
      {
        title: "Transaction by Account",
        key: "transaction_by_account",
        path: "/reports?type=transaction-by-account",
      }
    ],
  },
  {
    title: "Sales and Customers",
    key: "sales_and_customers",
    reports: [
      {
        title: "Sales by Customer Type",
        key: "sales_by_customer_type",
        path: "/reports?type=sales-by-customer-type",
      },
      {
        title: "Estimates & Progress Invoicing Summary by Customer",
        key: "estimates_and_progress_invoicing_summary_by_customer",
        path: "/reports?type=estimates-and-progress-invoicing-summary-by-customer",
      },
      {
        title: "Customer Contact List",
        key: "customer_contact_list",
        path: "/reports?type=customer-contact-list",
      },
      {
        title: "Income By Customer Summary",
        key: "income_by_customer_summary",
        path: "/reports?type=income-by-customer-summary",
      },
      {
        title: "Sales by Customer Summary",
        key: "sales_by_customer_summary",
        path: "/reports?type=sales-by-customer-summary",
      },
      {
        title: "Sales by Customer Detail",
        key: "sales_by_customer_detail",
        path: "/reports?type=sales-by-customer-detail",
      },
      {
        title: "Product/Service List",
        key: "product_service_list",
        path: "/reports?type=product-service-list",
      },
      {
        title: "Sales by Product/Service Summary",
        key: "sales_by_product_service_summary",
        path: "/reports?type=sales-by-product-service-summary",
      },
      {
        title: "Sales by Product/Service Detail",
        key: "sales_by_product_service_detail",
        path: "/reports?type=sales-by-product-service-detail",
      },
      {
        title: "Payment Method List",
        key: "payment_method_list",
        path: "/reports?type=payment-method-list",
      },
      {
        title: "Transaction List by Customer",
        key: "transaction_list_by_customer",
        path: "/reports?type=transaction-list-by-customer",
      },
    ],
  },
  {
    title: "Expenses and Vendors",
    key: "expenses_and_vendors",
    reports: [
      {
        title: "1099 Transaction Detail Report",
        key: "1099_transaction_detail_report",
        path: "/reports?type=1099-transaction-detail-report",
      },
      {
        title: "Transaction List by Vendor",
        key: "transaction_list_by_vendor",
        path: "/reports?type=transaction-list-by-vendor",
      },
      {
        title: "Vendor Contact List",
        key: "vendor_contact_list",
        path: "/reports?type=vendor-contact-list",
      },
      {
        title: "Expenses by Vendor Summary",
        key: "expenses_by_vendor_summary",
        path: "/reports?type=expenses-by-vendor-summary",
      },
    ],
  },
  {
    title: "Employees",
    key: "employees",
    reports: [
      {
        title: "Employee Contact List",
        key: "employee_contact_list",
        path: "/reports?type=employee-contact-list",
      },
      {
        title: "Time Activities by Employee Detail",
        key: "time_activities_by_employee_detail",
        path: "/reports?type=time-activities-by-employee-detail",
      },
    ],
  },
  {
    title: "For My Accountant",
    key: "for_my_accountant",
    reports: [
      {
        title: "Account List",
        key: "account_list",
        path: "/reports?type=account-list",
      },
      {
        title: "Balance Sheet",
        key: "balance_sheet",
        path: "/reports?type=balance-sheet",
      },
      {
        title: "Balance Sheet Comparison",
        key: "balance_sheet_comparison",
        path: "/reports?type=balance-sheet-comparison",
      },
      {
        title: "Profit & Loss",
        key: "profit_and_loss",
        path: "/reports?type=profit-and-loss",
      },
      {
        title: "Profit & Loss Comparison",
        key: "profit_and_loss_comparison",
        path: "/reports?type=profit-and-loss-comparison",
      },
      {
        title: "Recent Transactions",
        key: "recent_transactions",
        path: "/reports?type=recent-transactions",
      },
      {
        title: "Trial Balance",
        key: "trial_balance",
        path: "/reports?type=trial-balance",
      },
      {
        title: "Transaction Detail by Account",
        key: "transaction_detail_by_account",
        path: "/reports?type=transaction-detail-by-account",
      },
      {
        title: "Transaction List by Date",
        key: "transaction_list_by_date",
        path: "/reports?type=transaction-list-by-date",
      },
    ],
  },
];

export const filterDateOptions = [
  { title: "Today", value: "today" },
  { title: "Yesterday", value: "yesterday" },
  { title: "This week", value: "thisWeek" },
  { title: "Last week", value: "lastWeek" },
  { title: "This month", value: "thisMonth" },
  { title: "Last month", value: "lastMonth" },
  { title: "This quarter", value: "thisQuarter" },
  { title: "Last quarter", value: "lastQuarter" },
  { title: "Last 6 months", value: "last6Months" },
  { title: "Last 12 months", value: "last12Months" },
  { title: "This year", value: "thisYear" },
];
